### ISSUE TITLE
Finetuning on other dataset

### ISSUE THREAD

**Issue by Spectra456** [wenet-e2e/wespeaker#168]
Hi. How I can understand it's impossible to use a model which was trained on some larger dataset and then use it checkpoint to train on another small dataset, right?
When I'm trying this, I'm getting error:

```
wespeaker/wespeaker/utils/checkpoint.py", line 21, in load_checkpoint   
    model.load_state_dict(checkpoint, strict=False)                                                                                            
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict                                      
    self.__class__.__name__, "\n\t".join(error_msgs)))                                                                                         
RuntimeError: Error(s) in loading state_dict for ResNet:                                                                                       
        size mismatch for projection.weight: copying a param with shape torch.Size([26685, 256]) from checkpoint, the shape in current model is
 torch.Size([7548, 256]).                                                                                                                      

```
How I understand its output shape, but I don't understand, where these numbers are to come from (26685, 7548). My first guess was that, it's a number of speakers, but I don't have so many speakers in my datasets.

**Comment by JiJiJiang** [comment]
We support two types of ``checkpoints'' in our codes:
1. trained on large dataset and then finetuned on small dataset: set ``model_init`` as ``/the/path/to/large/dataset/model`` in your conf/xxx.yaml
![image](https://github.com/wenet-e2e/wespeaker/assets/23723621/69acd8ee-bd19-401b-8730-978a96ce6140)
2. training was aborted unexpectedly and start training from some specific epoch 
![image](https://github.com/wenet-e2e/wespeaker/assets/23723621/c42cea90-cd7e-4ab0-a489-0c883a7a3f9a)
The first one will train the projection layer from scratch as the training spk_num changes, while the second one will reuse it because the training set are the same. For your case, I think you should use the first strategy and remember to set the ``model_init`` parameter.

For your 2nd question, I guess you have used speed perturb augmentation in your training (default is true). Different speed is regarded as new speakers because the pitch is changed, so the training spk_num would be 3 * #spk of your datasets.
