### ISSUE TITLE
Kaldi Fbanks

### ISSUE THREAD

**Issue by Spectra456** [wenet-e2e/wespeaker#328]
Hi, thanks for repository!
I have 2 questions:
 1. Is there any specific reason why kaldi-fbanks was used to train/inference model? Did you tried other realizations, like from the torchaudio itself [MelSpectrogram](https://pytorch.org/audio/main/generated/torchaudio.transforms.MelSpectrogram.html)?
 2.  I understand that kaldifeat realization is the fastest open-source realization, but anyway it's slow down whole pipeline, even it's work on GPU, because of all this memory transactions between 2 models in Triton Server.
 I think fastest way to do it is to write a realization of fbanks on pure pytorch, convert it to ONNX and at the moment when we export speaker verification model to onnx, **combine  fbank onnx model and speaker verification onnx model**. It would prevent all unnecessary memory movements in Triton Server.

**Comment by JiJiJiang** [comment]
1. As you say, kaldifeat C++ realization is open-source and easy to use for deployment, which is much more convenient than [MelSpectrogram](https://pytorch.org/audio/main/generated/torchaudio.transforms.MelSpectrogram.html) in torchaudio.
2. Yes, since torchaudio.compliance.kaldi.fbank cannot directly be part of the model, I agree with you that write a realization of fbanks on pure pytorch may be the best way to fix this problem. And then only one onnx model is needed to be exported. However, due to the history reason, we need to do a lot of experiments. If you are interested in this, you are very welcomed to contribute. But first of all, the performance should totally match torchaudio.compliance.kaldi.fbank
