### ISSUE TITLE
Why use checkpoint instead of model_init during LMF

### ISSUE THREAD

**Issue by didi1233** [wenet-e2e/wespeaker#376]
Hi, thanks for your great contributions to WeSpeaker! I’ve been reviewing the training code, and from what I understand, ‘checkpoint’ is used to load the full model weights when resuming training after an interruption. On the other hand, ‘model_init’ is used to load parts of the weights (everything except for the projection layer), where the projection layer is initialized randomly for fine-tuning on a specific task.

My question is: why is ’checkpoint‘ used during the LMF (Large Margin Fine-tuning) stage instead of model_init? When the number of classes changes, the ’checkpoint‘ will also randomly initialize the projection layer (with ’strict=False‘), which seems similar to how ’model_init‘ works. What is the difference between the two approaches?

Additionally, if ’checkpoint‘ can continue training when the number of classes remains the same (and initialize the projection layer when the number of classes changes), what is the specific role of ’model_init‘?

Thank you very much for your clarification!

**Comment by JiJiJiang** [comment]
Hello, thanks for your good question!

1. The difference of `checkpoint` and `model_init` is exactly what you understood in your first paragraph. `checkpoint` is designed for training resuming after an interruption, which `model_init` is designed for training on dataset A and then fine-tuning on another dataset B, for example. 
2. `checkpoint` is loaded for both speaker model and projector, while `model_init` only loads the speaker model. If we use the `checkpoint` mode to load a checkpoint with different projector output size, the error occurs even `strict=False` is used (see the following picture). We load the speaker model before adding the projector layer in `model_init` mode, which avoids this problem.
3. Why `checkpoint` is used in LMF? We need the projection layer to be loaded rather than randomly initialized during LMF, but we only use its first 1/3 output nodes, so we set `speed_perturb=False` (https://github.com/wenet-e2e/wespeaker/blob/2751dd2caac42f5d58eea29b8b8f971cfb0ed0e5/wespeaker/bin/train.py#L142). This could not be done if using the `model_init` mode.

![image](https://github.com/user-attachments/assets/f37373b8-79b0-4b07-8e5b-dc7887a1f9f9)

**Comment by didi1233** [comment]
> Hello, thanks for your good question!
> 
> 
> 
> 1. The difference of `checkpoint` and `model_init` is exactly what you understood in your first paragraph. `checkpoint` is designed for training resuming after an interruption, which `model_init` is designed for training on dataset A and then fine-tuning on another dataset B, for example. 
> 
> 2. `checkpoint` is loaded for both speaker model and projector, while `model_init` only loads the speaker model. If we use the `checkpoint` mode to load a checkpoint with different projector output size, the error occurs even `strict=False` is used (see the following picture). We load the speaker model before adding the projector layer in `model_init` mode, which avoids this problem.
> 
> 3. Why `checkpoint` is used in LMF? We need the projection layer to be loaded rather than randomly initialized during LMF, but we only use its first 1/3 output nodes, so we set `speed_perturb=False` (https://github.com/wenet-e2e/wespeaker/blob/2751dd2caac42f5d58eea29b8b8f971cfb0ed0e5/wespeaker/bin/train.py#L142). This could not be done if using the `model_init` mode.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/f37373b8-79b0-4b07-8e5b-dc7887a1f9f9)
> 
> 

Thank you very much for your response. I have learned a lot from it. However, I still have one more question. In the third part of your response, the link you provided shows how speed perturbation is disabled and the projection layer’s number of classes is changed. But I don’t quite understand in which part of the code you use only the first 1/3 of the projection layer’s nodes?

**Comment by JiJiJiang** [comment]
We still preserve all projection layer's node. Since `speed_perturb=False`, the data pipeline only produces training samples without speed perturb, i.e. speed is always 1.0. Therefore, during LMF, only the first 1/3 classes have corresponding training samples while the last 2/3 classes will not.
